menu:
    Home: https://www.daigotanaka.com
    Blog: /
    Archive: /archives/

title: Daigo Tanaka
keywords: blog, english, japanese
description: Daigo Tanaka's essays and blog
# Copyright Infomation
startyear: 2009
