menu:
    Home: /
    Archive: /archives/
    日本語: https://www.daigotanaka.com/ja

title: Daigo Tanaka
keywords: blog, english, japanese
description: Daigo Tanaka's essays and blog
# Copyright Infomation
startyear: 2009
